=== ESRogs/cypress/resources/schematron/qrda/qrda_cat_1/measure_specific/measureMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com) by Richard Geimer (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="measureMap">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="measure">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name"/>
							<xs:element name="setId" type="II"/>
							<xs:element name="version" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="versionNumber"/>
										<xs:element name="id" type="II"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="II">
		<xs:attribute name="root"/>
		<xs:attribute name="extension"/>
	</xs:complexType>
</xs:schema>

=== ESRogs/cypress/resources/schematron/qrda/qrda_cat_1/measure_specific/measureMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<measureMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:/Users/rickg/workspaces-svn/ClientProjects/QRDATesting/measure-specific-schematron/measureMap.xsd">
	<measure>
		<name>Aspirin Prescribed at Discharge</name>
		<setId root="bb481284-30dd-4383-928c-82385bbf1b17"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0d01c6626e46"/>
		</version>
	</measure>
	<measure>
		<name>Assessed for Rehabilitation</name>
		<setId root="7dc26160-e615-4cc2-879c-75985189ec1a"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-01954afc63b2"/>
		</version>
	</measure>
	<measure>
		<name>Discharged on Antithrombotic Therapy</name>
		<setId root="42bf391f-38a3-4c0f-9ece-dcd47e9609d9"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-37bf-6f1b-0137-cdadba302b85"/>
		</version>
	</measure>
	<measure>
		<name>Discharged on Statin Medication</name>
		<setId root="1f503318-bb8d-4b91-af63-223ae0a2328e"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-37d1-f95b-0137-e776b0467baf"/>
		</version>
	</measure>
	<measure>
		<name>Stroke Education</name>
		<setId root="217fdf0d-3d64-4720-9116-d5e5afa27f2c"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3a00-2a25-013a-0dd50ce621d8"/>
		</version>
	</measure>
	<measure>
		<name>Venous Thromboembolism Prophylaxis</name>
		<setId root="38b0b5ec-0f63-466f-8fe3-2cd20ddd1622"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-01a1d2c966bc"/>
		</version>
	</measure>
	<measure>
		<name>Venous Thromboembolism Patients Receiving Unfractionated Heparin with Dosages/Platelet Count Monitoring by Protocol or Nomogram</name>
		<setId root="bcce43dd-08e3-46c3-bfdd-0b1b472690f0"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-01959fb76498"/>
		</version>
	</measure>
	<measure>
		<name>Venous Thromboembolism Discharge Instructions</name>
		<setId root="7fe69617-fa28-4305-a2b8-ceb6bcd9693d"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0138-9b2eaba7321d"/>
		</version>
	</measure>
	<measure>
		<name>Median Admit Decision Time to ED Departure Time for Admitted Patients</name>
		<setId root="979f21bd-3f93-4cdd-8273-b23dfe9c0513"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0c4e00454b35"/>
		</version>
	</measure>
	<measure>
		<name>Elective Delivery</name>
		<setId root="fd7ca18d-b56d-4bca-af35-71ce36b15246"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-01965ecf65be"/>
		</version>
	</measure>
	<measure>
		<name>Incidence of Potentially-Preventable Venous Thromboembolism</name>
		<setId root="32cfc834-843a-4f45-b359-8e158eac4396"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-018ce6f1622a"/>
		</version>
	</measure>
	<measure>
		<name>Prophylactic Antibiotic Received Within One Hour Prior to Surgical Incision</name>
		<setId root="d09add1d-30f5-462d-b677-3d17d9ccd664"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-39ca-af4b-0139-dfaaffd96efe"/>
		</version>
	</measure>
	<measure>
		<name>Prophylactic Antibiotic Selection for Surgical Patients</name>
		<setId root="feea3922-f61f-4b05-98f9-b72a11815f12"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-37d1-f95b-0137-e1e272994b3f"/>
		</version>
	</measure>
	<measure>
		<name>Urinary catheter removed on Postoperative Day 1 (POD 1) or Postoperative Day 2 (POD 2) with day of surgery being day zero</name>
		<setId root="d78ce034-8288-4012-a31e-7f485a74f2a9"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3a58-b777-013a-670ab6932a3b"/>
		</version>
	</measure>
	<measure>
		<name>Healthy Term Newborn</name>
		<setId root="ff796fd9-f99d-41fd-b8c2-57d0a59a5d8d"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3a00-2a25-013a-295ed21c463c"/>
		</version>
	</measure>
	<measure>
		<name>Initial Antibiotic Selection for Community-Acquired Pneumonia (CAP) in Immunocompetent Patients</name>
		<setId root="8243eae0-bbd7-4107-920b-fc3db04b9584"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3a58-b777-013a-716dfc096ee3"/>
		</version>
	</measure>
	<measure>
		<name>Intensive Care Unit Venous Thromboembolism Prophylaxis</name>
		<setId root="fa91ba68-1e66-4a23-8eb2-baa8e6df2f2f"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3a00-2a25-013a-4640d11650cb"/>
		</version>
	</measure>
	<measure>
		<name>Home Management Plan of Care (HMPC) Document Given to Patient/Caregiver</name>
		<setId root="e1cb05e0-97d5-40fc-b456-15c5dbf44309"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-37bf-6f1b-0137-ccd612a40d0e"/>
		</version>
	</measure>
	<measure>
		<name>Statin Prescribed at Discharge</name>
		<setId root="ebfa203e-acc1-4228-906c-855c4bf11310"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0d071ee37793"/>
		</version>
	</measure>
	<measure>
		<name>Hearing Screening Prior To Hospital Discharge (EHDI-1a)</name>
		<setId root="0924fbae-3fdb-4d0a-aab7-9f354e699fde"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-12364ae9126f"/>
		</version>
	</measure>
	<measure>
		<name>Median Time from ED Arrival to ED Departure for Discharged ED Patients</name>
		<setId root="3fd13096-2c8f-40b5-9297-b714e8de9133"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-37d1-f95b-0137-dd4b0eb62de6"/>
		</version>
	</measure>
	<measure>
		<name>Primary PCI Received Within 90 Minutes of Hospital Arrival</name>
		<setId root="84b9d0b5-0caf-4e41-b345-3492a23c2e9f"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0d08a4be7be6"/>
		</version>
	</measure>
	<measure>
		<name>Median Time from ED Arrival to ED Departure for Admitted ED Patients</name>
		<setId root="9a033274-3d9b-11e1-8634-00237d5bf174"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0c4e41594c98"/>
		</version>
	</measure>
	<measure>
		<name>Fibrinolytic Therapy Received Within 30 Minutes of Hospital Arrival</name>
		<setId root="909cf4b4-7a85-4abf-a1c7-cb597ed1c0b6"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-11b262260a92"/>
		</version>
	</measure>
	<measure>
		<name>Anticoagulation Therapy for Atrial Fibrillation/Flutter</name>
		<setId root="03876d69-085b-415c-ae9d-9924171040c2"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-013b0c87524a"/>
		</version>
	</measure>
	<measure>
		<name>Antithrombotic Therapy By End of Hospital Day 2</name>
		<setId root="93f3479f-75d8-4731-9a3f-b7749d8bcd37"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0c49fb8c4757"/>
		</version>
	</measure>
	<measure>
		<name>Venous Thromboembolism Patients with Anticoagulation Overlap Therapy</name>
		<setId root="6f069bb2-b3c4-4bf4-adc5-f6dd424a10b7"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0c4e6d2b4d6b"/>
		</version>
	</measure>
	<measure>
		<name>Thrombolytic Therapy</name>
		<setId root="2838875a-07b5-4bf0-be04-c3eb99f53975"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-3887-5df3-0139-0c0d3d783133"/>
		</version>
	</measure>
	<measure>
		<name>Exclusive Breast Milk Feeding</name>
		<setId root="7d374c6a-3821-4333-a1bc-4531005d77b8"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-37d1-f95b-0137-e726ad2f7415"/>
		</version>
	</measure>
	<measure>
		<name>Childhood Immunization Status</name>
		<setId root="b2802b7a-3580-4be8-9458-921aea62b78c"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-39ca-af4b-0139-cae9ed8a01bd"/>
		</version>
	</measure>
	<measure>
		<name>Diabetes: Hemoglobin A1c Poor Control</name>
		<setId root="f2986519-5a4e-4149-a8f2-af0a1dc7f6bc"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-397a-48d2-0139-9cd4937e6c86"/>
		</version>
	</measure>
	<measure>
		<name>Diabetes: Foot Exam</name>
		<setId root="c0d72444-7c26-4863-9b51-8080f8928a85"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-397a-48d2-0139-7ccb48f6025d"/>
		</version>
	</measure>
	<measure>
		<name>Cervical Cancer Screening</name>
		<setId root="42e7e489-790f-427a-a1a6-d6e807f65a6d"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-397a-48d2-0139-b0cba8db32c3"/>
		</version>
	</measure>
	<measure>
		<name>Breast Cancer Screening</name>
		<setId root="19783c1b-4fd1-46c1-8a96-a2f192b97ee0"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-397a-48d2-0139-b0cadcb63221"/>
		</version>
	</measure>
	<measure>
		<name>Use of Appropriate Medications for Asthma</name>
		<setId root="59e84144-6332-4369-aebd-03a7899ca3da"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-397a-48d2-0139-c648b33d5582"/>
		</version>
	</measure>
	<measure>
		<name>Pneumonia Vaccination Status for Older Adults</name>
		<setId root="59657b9b-01bf-4979-a090-8534da1d0516"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-35fb-4aa7-0136-5a26000d30bd"/>
		</version>
	</measure>
	<measure>
		<name>Anti-depressant Medication Management</name>
		<setId root="8924f2b3-ec06-4650-b634-d70a53dee577"/>
		<version>
			<versionNumber>1</versionNumber>
			<id root="8a4d92b2-39ca-af4b-0139-caf11e27054e"/>
		</version>
	</measure>
	<measure>
		<name>Prostate Cancer: Avoidance of Overuse of Bone Scan for Staging Low Risk Prostate Cancer Patients</name>
		<setId root="1635c14d-e612-4fa6-96cd-285361aa7f7b"/>
		<version>
			<versionNumber>1</versionNumber>
